function animateOptTraj(x,dt)
% x: collection of state vectors at each time, similar to output from ode45
% dt: (difference in time between each row of xout, generated by calling
% Define axis window
xmin = 0;
xmax = 10;
ymin = 0;
ymax = 10;
bRecord = 0;  % Uncomment this to save a video
Fig = figure('Color', 'w');
% Create trace of trajectory and particle object
h = animatedline('LineStyle', '--', 'LineWidth', 1.5);

% Set up axes
axis equal
axis([xmin xmax ymin ymax])
xlabel('x')
ylabel('y')

for ii = 1:length(x)
    a = tic;
    set(gcf,'DoubleBuffer','on');
%     delete(robot);
    x1 = x(ii,1);
    y = x(ii,2);
    psi = x(ii,3);
%     delta_f = x(ii,end);
    robot_x = [x1*cos(psi) + y*sin(psi)];
    robot_y = [-x1*sin(psi) + y*cos(psi)];
%     robot_pos = [robot_x; robot_y];
%     robot = line([base(1),robot_pos(1)],[base(2),robot_pos(2)], 'Color', [0;0;0],'LineStyle','-');
    
    addpoints(h,robot_x,robot_y);
    
    drawnow limitrate
    
    if bRecord
        frame = getframe(gcf);
        writeVideo(v,frame);
    else
        pause(dt - toc(a)); % waits if drawing frame took less time than anticipated
    end
end

end

