function [A,B,C,D,E,F] = computeDynamicMatrices(x)
%COMPUTEDYNAMICMATRICES
%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Nov-2018 15:48:06

l = 1; w = 0.5; h = 0.3; % Vehicle Dimensions in metres
lf = l/0.5; lr = l/0.5;
mg = 50;
m = 50/9.81;
Cf = mg*0.60*0.165; % cornering stiffness for front wheels
Cr = mg*0.40*0.165;% cornering stiffness for rear wheels
Iz = m/12*(l^2 + w^2);
delta_f = x(1,end);
xd = x(1,4);
A = - (( Cf *cos(delta_f) + Cr)/(m*xd));
B =  ((-lf*Cf*cos(delta_f) + lr*Cr)/(m*xd))-xd;
C = ((-lf*Cf*cos(delta_f) + lr*Cr)/(Iz*xd));
D = -((lf^2 *Cf*cos(delta_f) + lr^2 *Cr)/(Iz*xd));
E = Cf*cos(delta_f)/m;
F = lf*Cf*cos(delta_f)/Iz;
end